- name: "bug"
  color: "d73a4a"
  description: "Bug或错误"

- name: "enhancement"
  color: "a2eeef"
  description: "新功能或改进"

- name: "documentation"
  color: "0075ca"
  description: "文档相关"

- name: "good first issue"
  color: "7057ff"
  description: "适合新手的Issue"

- name: "help wanted"
  color: "008672"
  description: "需要帮助"

- name: "priority:high"
  color: "b60205"
  description: "高优先级"

- name: "priority:medium"
  color: "fbca04"
  description: "中优先级"

- name: "priority:low"
  color: "0e8a16"
  description: "低优先级"

- name: "status:blocked"
  color: "000000"
  description: "被阻塞"

- name: "status:in progress"
  color: "cccccc"
  description: "进行中"

- name: "type:feature"
  color: "5319e7"
  description: "功能类型"

- name: "type:bug"
  color: "b60205"
  description: "Bug类型"

- name: "type:refactor"
  color: "0052cc"
  description: "重构类型"
